unit_sheet: "config/units.tsv"

resources:
  ref:
    species: saccharomyces_cerevisiae
    host_species: caenorhabditis_elegans
    release: "115"
    build: R64-1-1
    host_build: WBcel235

xengsort:
  index:
    nobjects: 113000000
    kmersize: 25
    bucketsize: 4
    fill: 0.85
