$schema: "https://json-schema.org/draft/2020-12/schema"
type: object
description: main configuration schema for the workflow
properties:
  unit_sheet:
    type: string
    description: path to sample sheet, mandatory
    default: config/samples.tsv

  resources:
    type: object
    properties:
      ref:
        type: object
        properties:
          species:
            type: string
          host_species:
            type: string
          release:
            type: string
          build:
            type: string
        required:
          - species
          - host_species
          - release
          - build

  xengsort:
    type: object
    properties:
      index:
        type: object
        properties:
          nobjects:
            type: integer
            description: number of k-mers to store in the hash table
          kmersize:
            type: integer
            description: size of k-mers to store in the hash table
          bucketsize:
            type: integer
            description: number of elements that can be stored in an individual bucket
          fill:
            type: number
            description: desired fill rate of the hash table
        required:
          - nobjects
          - kmersize
          - bucketsize
          - fill
    required:
      - index

required:
  - unit_sheet
  - resources
  - xengsort
