$schema: "https://json-schema.org/draft/2020-12/schema"
type: object
description: main configuration schema for the workflow
properties:
  unit_sheet:
    type: string
    description: path to sample sheet, mandatory
    default: config/samples.tsv

  resources:
    type: object
    properties:
      ref:
        type: object
        properties:
          release:
            type: string
            description: Ensembl release to use
          species:
            type: string
            description: Ensembl name of grafted species
          host_species:
            type: string
            description: Ensembl name of host species
          build:
            type: string
            description: build of grafted species
          host_build:
            type: string
            description: build of host species
        required:
          - release
          - species
          - host_species
          - build
          - host_build

  xengsort:
    type: object
    properties:
      index:
        type: object
        properties:
          nobjects:
            type: integer
            description: number of k-mers to store in the hash table
          kmersize:
            type: integer
            description: size of k-mers to store in the hash table
          bucketsize:
            type: integer
            description: number of elements that can be stored in an individual bucket
          fill:
            type: number
            description: desired fill rate of the hash table
        required:
          - nobjects
          - kmersize
          - bucketsize
          - fill
    required:
      - index

required:
  - unit_sheet
  - resources
  - xengsort
